### ISSUE TITLE
ERR_INCOMPLETE_CHUNKED_ENCODING

### ISSUE THREAD

**Issue by nokome** [stencila/sibyl#34]
For long launches this messages comes up in Chrome. May be to do with Nginx proxy timeout

![image](https://user-images.githubusercontent.com/1152336/27380527-913e6134-56d3-11e7-921c-bb7b2aa76286.png)

**Comment by yoshuawuyts** [comment]
feel like I've run into this before in the past, remembered it had
something to do with headers not set. A quick search shows it could perhaps
be b/c Content-Length is not being set correctly.

**Comment by nokome** [comment]
I think these could be useful:

- https://stackoverflow.com/a/13673298/4625911
- https://serverfault.com/a/801629

**Comment by nokome** [comment]
@yoshuawuyts : can you catch errors like this a give the user an "aw snap, something went wrong" apology?

**Comment by finlay** [comment]
I have updated the nginx config.

Stored as a configmap  called nginx-sse.

I think this should be fixed. It would be good to see a case where was failing previously.

**Comment by nokome** [comment]
I got this error again after a fresh deployment and fresh `alpha` image. Got as far as trying to build the bundle image (which is where is seems to fail pulling down the image)

```
INFO Changed to directory '/usr/app/bundles/github-stencila-examples-diamonds-0f4489059b'
INFO Fetching scheme 'github' with path 'stencila/examples/diamonds'
INFO Fetching Github repo 'stencila/examples' folder 'diamonds'
tar: write error
INFO Fetching from file archive '/usr/app/tmp.HckzuoFpGc/archive.tar.gz' folder 'stencila-examples-76fe6d5/diamonds'
Listed 0 items.
INFO Building image: 'gcr.io/stenci.la/api-project-72315317623/github-stencila-examples-diamonds-0f4489059b:4ca2212ada27f0f7c01939b2b484a214ada6cb37'
```

**Comment by nokome** [comment]
Closing this for now. If it happens again it belongs in https://github.com/stencila/open.
