### ISSUE TITLE
Occaisional long launch times

### ISSUE THREAD

**Issue by nokome** [stencila/sibyl#35]
The `stencila/alpha` image is large and takes a long time to download, even on GKE. That's OK, because each `sibyl-server` container can download it. But when a new `stencila/alpha:latest` is built, or a new `sibyl-server` is scaled up. The first bundle image build takes a very long time.

**Comment by yoshuawuyts** [comment]
If I recall correctly, one of the problems of the docker daemon is that it
has rather unpredictable boot times. I don't know if that's the cause here,
but if it is it might not necessarily be a solvable problem (besides
figuring out ways to work around it).

**Comment by nokome** [comment]
All the behaviour I am seeing points to this being related to `docker build ...` having to pull an updated image of `alpha`.

**Comment by finlay** [comment]
Just some questions:

Is this related to the call at line 517 of sibyl.sh ?
If so, is it possible to provide more feedback about the docker pull ?
Oh, is the problem here that it is just taking too long, or is it causing some other problem ?

**Comment by nokome** [comment]
Yeah, it seems that if just takes a long time and then the chunked encoding
error thing happens so you never get the link to the session.
