### ISSUE TITLE
No ~ in stencila/iota image

### ISSUE THREAD

**Issue by nokome** [stencila/sibyl#36]
When developing locally `SIBYL_FROM=stencila/iota` - a small image which is faster to load that the huge `alpha`. Iota is based on `alpine` which doesn't support tilde expansion. That means that when using iota instead of navigating to `.../~` you need to go to `.../file:///home/guest` (yes, triple forward slash).

**Comment by yoshuawuyts** [comment]
This is also the case in the diamond example. Any ideas on how to best detect this?

**Comment by nokome** [comment]
@yoshuawuyts : it's not the diamonds example that its broken, it's that the `iota` image doesn't support tilde expansion. A workaround is to use `SIBYL_FROM=stencila/alpha` env var so that `alpha` image is used as base.

Will look into longer term solution by fixing `iota` - perhaps by setting `USER` env var inside that image's Dockerfile?

**Comment by nokome** [comment]
This should be fixed by 0ceee36fd85b74340231caccfe3915240b3edd58. You'll have to `docker pull stencila/iota`.

Unfortunately we've introduced another bug that is getting fixed as I type this: https://github.com/stencila/node/issues/19
