### ISSUE TITLE
Term for URL and buttons: via, launch, open?

### ISSUE THREAD

**Issue by nokome** [stencila/sibyl#47]
@yoshuawuyts and @nokome discussed the URL for Sibyl last night. We don't want it to be http://sibyl.stenci.la, that just introduces another name to the user. 

Currently it's http://via.stenci.la (yes, inspired by hypothes.is) but that requires a couple of steps to work out. Yoshua suggested http://launch.stenci.la as a more explicit alternative. We would use the same term in the embedding buttons we provide e.g. `<a href="http://launch.stenci.la/github://...">Launch in Stencila</a>`

I think "launch" is good but thought that "open" might be a more familiar concept to people who are used to "opening" documents in office suites etc. It also references the open science, open source nature of Stencila. "Mock ups" ...

http://open.stenci.la

`[Open in Stencila](http://open.stenci.la/github://...)`

`<a href="http://open.stenci.la/github://...">Open in Stencila</a>`

Also pinging @michael and @oliver---- here for there thoughts.

I'd like to change this in the next 24hrs, so if you have comments, please give them soon :heart:

**Comment by oliver----** [comment]
I prefer http://open.stenci.la

**Comment by nokome** [comment]
Now http://open.stenci.la. Thanks!
