### ISSUE TITLE
Email hook

### ISSUE THREAD

**Issue by nokome** [stencila/sibyl#51]
The feature roadmap includes using web hooks to trigger builds (i.e rendering) of documents in response to events (e.g. push to Github). Builds of documents will include testing that all code cells run without errors and possibly generation of a static PDF of the document watermarked with a date and container id.

User might like to have an email hook: send an email to open@stenci.la with a document bundle attached as several files or a zip file, Sibyl will build it and send you back an email with the result.

**Comment by yoshuawuyts** [comment]
Think the steps for this are:
- [ ]  build out sibyl.js so we can more easily call this logic
- [ ] hook into an email provider (such as sendgrid) to get transactional emails done (yay for spam filters otherwise >.>)
- [ ] hook up the things

**Comment by nokome** [comment]
The more I think about this the more I think it could be really useful. The "email docs among collegues" workflow is so pervasive amongst researchers. Instead of trying to convince them to adopt a different workflow (Git repo + Travis CI) overnight we could add value to their existing workflow.

Bob emails Alice: "I changed some text in the second paragraph and fixed the third code cell" and attaches a  `.md` file and a `.csv` file and cc's open@stenci.la. Sibyl runs the document within todays image (or a image pinned to a date) and emails them both back with the results (% of cells erroring, perhaps a static PDF). Sibyl becomes a CI collaborator in the email conversation. Using https://github.com/maxogden/conversationThreading-js or similar we could construct a build history for the conversation.

**Comment by yoshuawuyts** [comment]
Oh, yeah that's a good point actually - digging this!

**Comment by nokome** [comment]
Moved to stencila/open#7
