### ISSUE TITLE
Placeholder development beta token appears in production

### ISSUE THREAD

**Issue by nokome** [stencila/sibyl#56]
In `form.js` there is:

```js
    // Set a default value for the form during development
    if (process.env.NODE_ENV !== 'production') {
      validator.validate('token', 'platypus')
      emitter.emit('render')
    }
```

but it aint working. Where should we set `process.env.NODE_ENV`? In`package.json.scripts.build`?

**Comment by yoshuawuyts** [comment]
Oh, that's just an env var. E.g. we should do ‘NODE_ENV=production bankai
build’ in our package json build script
