### ISSUE TITLE
File uploads

### ISSUE THREAD

**Issue by nokome** [stencila/sibyl#6]
The Bash script allows you to fetch a bundle from a file or directory on the local filesystem e.g.

```sh
sibyl fetch file://some/folder
sibyl fetch file://some.tar.gz
```
We should give users of the web UI similar functionality by allowing them to upload files, either as a single file, a collection of files, or a file archive. This would save the uploaded files to some temporary directory and then get `sibyl.sh` to fetch them from there.

We would need to give the user a bundle link e.g. `http://sibyl.stenci.la/fqwuy7t45de42:a43bc432` so that they could share that document bundle with friends. Someone visiting the link would get redirected to a new container with that bundle image.

**Comment by nokome** [comment]
@yoshuawuyts : just pinging you here to remind you to think about integrating this into the UI :smiley: . We can discuss in :gb:

**Comment by yoshuawuyts** [comment]
@nokome cool, yeah sounds useful - this would def require refactoring the form stuff I did yesterday to actually leverage form semantics + validation haha. Keen to talk about this tomorrow :D

**Comment by yoshuawuyts** [comment]
Going to build this off:
- https://github.com/yoshuawuyts/validate-formdata/
- https://github.com/yoshuawuyts/multipart-read-stream

**Comment by nokome** [comment]
Not an immediate priority, but it would be good to enable drag and drop file uploads at some time. Just noting it now so that whatever approach we use allows for that now or later.

**Comment by nokome** [comment]
Closing, done as part of https://github.com/stencila/open
