### ISSUE TITLE
Split into separate CLI, service and image repos/modules?

### ISSUE THREAD

**Issue by nokome** [stencila/sibyl#62]
We've currently mixing at least two, maybe three, use cases in the same repo/module. With a move from `sibyl.sh` to `sibyl.js` it makes more sense to split into three repos for separate use cases:

- `stencila/sibyl` repo and `stencila-sibyl` npm module for the CLI tool: folders `bin`, `lib`, ... - for developers and advanced users who have docker installed and want to use the CLI
- `stencila/open` repo and `stencila-open` npm module for the service: folders `server`, `client`, ... - for users who don't want to install anything and instead use the UI at open.stenci.la
- `stencila/images` repo for base images - Docker for now (but potentially other image formats e.g. SIngularity in the future) - folder `images` - this is orthogonal to the other two use cases (i.e. both CLI and open.stenci.la users will use images)

@yoshuawuyts and @finlay : let me know what you think. I'd do a subdirectory import thing to retain the existing commit histories.

**Comment by yoshuawuyts** [comment]
Yeah this would make sense I think ✨ - also helps us keep our dependencies
nice and organized (:

**Comment by nokome** [comment]
Have done this, and remove unused repos in bce02776322a91f700ed5b36347650492f82b48d

Created https://github.com/stencila/open using:
```sh
git clone git@github.com:stencila/sibyl open
git filter-branch --index-filter 'git rm --cached -qr --ignore-unmatch -- . && git reset -q $GIT_COMMIT -- server client deploy' --prune-empty -- --all
```

Created https://github.com/stencila/images using
```sh
git clone git@github.com:stencila/sibyl images
git filter-branch --prune-empty --subdirectory-filter images
```
