### ISSUE TITLE
Fetch a dat

### ISSUE THREAD

**Issue by nokome** [stencila/sibyl#8]
Add a `fetch_dat` function that could be used to fetch a document bundle from within a dat e.g.

```sh
sibyl fetch dat://778f8d955175c92...
sibyl fetch dat://778f8d955175c92.../folder
```

**Comment by maxogden** [comment]
made PR for the first line in the example above: https://github.com/stencila/sibyl/pull/29

**Comment by nokome** [comment]
At this stage the subfolder pattern is not supported. But closing this for now.

Thanks again for your help @maxogden!
